name: AWS Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    TF_VAR_S3_NAME: "my-unique-bucket-name"
    TF_VAR_REGION: "eu-central-1"

jobs:
    Terraform:
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: terraform
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.7.5

            - name: Setup AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.TF_VAR_REGION }}
        
            - name: Terraform Init
              run: terraform init
            - name: Terraform Plan
              run: terraform plan
              env:
                TF_VAR_s3_name: ${{ env.TF_VAR_S3_NAME  }}
                TF_VAR_region: ${{ env.TF_VAR_REGION }}
            - name: Terraform Apply
              run: terraform apply -auto-approve